[program:jnu-link-backend]
command=python app.py
directory=/var/www/jnu-link/backend
environment=FLASK_ENV="production"
user=www-data
stdout_logfile=/var/log/jnu-link/backend.log
stderr_logfile=/var/log/jnu-link/backend_error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
autostart=true
autorestart=true
startsecs=5
stopwaitsecs=10
priority=999
